[package]
name = "tcr-io"
version = "0.5.0-beta.6"
edition = "2021"

[lib]
name = "tcr_io"
crate-type= ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.0", features = ["extension-module", "abi3-py310"] }
pyo3-polars = { version = "0.26.0", features = ["derive", "dtype-struct", "dtype-array"] }
serde = { version = "1", features = ["derive"] }
polars = { version = "0.53.0", features=["dtype-struct"], default-features = false}
polars-arrow = { version = "0.53.0", default-features = false }
num-traits = "0.2.19"
aho-corasick = "1.1.4"
rayon = "1"
